language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: swoeste-github
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
